version: "3.8"

services:

  dispatcher:
    build:
      context: .
      dockerfile: dispatcher/Dockerfile
    container_name: dispatcher
    ports:
      - "8000:8000"
    depends_on:
      - worker1
      - worker2
      - worker3

  worker1:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker1

  worker2:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker2

  worker3:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker3
